vim.api.nvim_create_user_command('PackerInstall', function()
	require('lazy').install()
end, {})
vim.api.nvim_create_user_command('PackerUpdate', function()
	require('lazy').update()
end, {})
vim.api.nvim_create_user_command('PackerSync', function()
	require('lazy').sync()
end, {})
vim.api.nvim_create_user_command('PackerClean', function()
	require('lazy').clean()
end, {})
vim.api.nvim_create_user_command('PU', 'PackerSync', {})
